@ECHO OFF
REM Autogenerated by FlexAdmin to run a used supplied script
REM Source script was flexadmin.ps1
REM Working Folder was C:\Crayon\ImplFiles
REM Created at 15/12/2020 16:13

REM Change to directory containing this file
CD /D %~dp0

REM Run the PowerShell command line as Admin
PowerShell -NoProfile -ExecutionPolicy Bypass "& .\flexadmin.ps1 InstallAll -FlexAdminPath C:\Crayon\ImplFiles"

pause
